apiVersion: 1

datasources:
- name: Timescale
  type: postgres
  access: proxy
  orgId: 1
  url: timescale:5432
  database: "powerwatch"
  user: "${GRAFANA_DATABASE_USER_CLEAR}"
  secureJsonData:
    password: "${GRAFANA_DATABASE_PASSWORD_CLEAR}"
  jsonData:
    sslmode: 'disable'
    postgresVersion: 906
    timescaledb: true
    timeInterval: '1s'
  version: 1
  editable: false

- name: Influx
  type: influxdb
  access: proxy
  orgId: 1
  url: http://influx:8086
  user: "${GRAFANA_DATABASE_USER_CLEAR}"
  password: "${GRAFANA_DATABASE_PASSWORD_CLEAR}"
  database: "powerwatch"
  version: 1
  editable: false
  jsonData:
    timeInterval: '1s'
