{
 "title": "Powerwatch_General",
 "time": { "from": "2018-10-30T00:25:39.527Z", "to": "2018-11-03T00:25:39.527Z" },
 "panels": [
  {
   "title": "Status Table",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  core_id, \n  min(current_timestamp - time) as \"Lag\",\n  CAST(extract(epoch from min(current_timestamp - time)) AS INTEGER) as \"Lag_Seconds\",\n  ROW_NUMBER() OVER (ORDER BY min(current_timestamp - time) DESC, core_id)\nFROM powerwatch\nGROUP BY \n  core_id\nORDER BY \n  \"Lag\" ASC,\n  core_id\n\n"
    }
   ]
  },
  {
   "title": "Devices with Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Num devices powered" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "core_id" ], "type": "tag" }
     ],
     "measurement": "is_powered",
     "rawSql": "SELECT  \n  time_bucket('10 minutes', time) AS \"time\",\n  count(distinct core_id) AS \"powered\"\nFROM\n  powerwatch\nWHERE\n  $__timeFilter(time) AND \"is_powered\" = true\nGROUP BY time_bucket('10 minutes', time)\n\n"
    },
    {
     "groupBy": [
      { "params": [ "core_id" ], "type": "tag" }
     ],
     "measurement": "is_powered",
     "rawSql": "SELECT  \n  time_bucket('10 minutes', time) AS \"time\",\n  count(distinct core_id) AS \"reporting\"\nFROM\n  powerwatch\nWHERE\n  $__timeFilter(time)\nGROUP BY time_bucket('10 minutes', time)\n\n"
    },
    {
     "groupBy": [
      { "params": [ "core_id" ], "type": "tag" }
     ],
     "measurement": "is_powered",
     "rawSql": "SELECT  \n  time_bucket('10 minutes', time) AS \"time\",\n  count(distinct core_id) AS \"not powered\"\nFROM\n  powerwatch\nWHERE\n  $__timeFilter(time) AND \"is_powered\" = false\nGROUP BY time_bucket('10 minutes', time)\n\n"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "core_id" ], "type": "tag" }
     ],
     "measurement": "cell_voltage",
     "rawSql": "SELECT\n  time_bucket('10 minutes', time) as \"time\",\n  core_id as \"metric\",\n  max(cell_voltage)\nFROM\n  powerwatch\nWHERE\n  $__timeFilter(time)\nGROUP BY time_bucket('10 minutes', time), core_id\nORDER BY metric asc, time asc\n\n"
    }
   ]
  },
  {
   "title": "State of Charge",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "core_id" ], "type": "tag" }
     ],
     "measurement": "state_of_charge",
     "rawSql": "SELECT\n  time_bucket('10 minutes', time) as \"time\",\n  core_id as \"metric\",\n  max(state_of_charge)\nFROM\n  powerwatch\nWHERE\n  $__timeFilter(time)\nGROUP BY time_bucket('10 minutes', time), core_id\nORDER BY metric asc, time asc"
    }
   ]
  },
  {
   "title": "Is Powered",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "core_id" ], "type": "tag" }
     ],
     "measurement": "state_of_charge",
     "rawSql": "SELECT\n  time_bucket('10 minutes', time) as \"time\",\n  core_id as \"metric\",\n  max(CAST(is_powered as INTEGER))\nFROM\n  powerwatch\nWHERE\n  $__timeFilter(time)\nGROUP BY time_bucket('10 minutes', time), core_id\nORDER BY metric asc, time asc\n"
    }
   ]
  },
  {
   "title": "GPS Satellites",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "core_id" ], "type": "tag" }
     ],
     "measurement": "state_of_charge",
     "rawSql": "SELECT\n  time_bucket('10 minutes', time) as \"time\",\n  core_id as \"metric\",\n  max(CAST (gps_satellites as INTEGER))\nFROM\n  powerwatch\nWHERE\n  $__timeFilter(time)\nGROUP BY time_bucket('10 minutes', time), core_id\nORDER BY metric asc, time asc\n"
    }
   ]
  },
  {
   "title": "SD Log Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "core_id" ], "type": "tag" }
     ],
     "measurement": "sd_log_size",
     "rawSql": "SELECT\n  time_bucket('10 minutes', time) as \"time\",\n  core_id as \"metric\",\n  max(sd_log_size)\nFROM\n  powerwatch\nWHERE\n  $__timeFilter(time) AND sd_log_size is not null\nGROUP BY time_bucket('10 minutes', time), core_id\nORDER BY metric asc, time asc"
    }
   ]
  },
  {
   "title": "Error States",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "core_id" ], "type": "tag" }
     ],
     "measurement": "error_state",
     "rawSql": "SELECT\n  time_bucket('10 minutes', time) as \"time\",\n  core_id as \"metric\",\n  max(error_state)\nFROM\n  powerwatch_error\nWHERE\n  $__timeFilter(time)\nGROUP BY time_bucket('10 minutes', time), core_id\n",
     "tags": [
      { "key": "product_id", "operator": "=", "value": "7008" },
      { "condition": "OR", "key": "product_id", "operator": "=", "value": "7009" }
     ]
    }
   ]
  },
  {
   "title": "# Reporting in Last 15 minutes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 66 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  to_timestamp((CAST(extract(epoch from time) as INTEGER)/900)*900) AS \"time\",\n  count(distinct core_id) \nFROM\n  powerwatch\nWHERE\n  (time > now() - INTERVAL '15m')\n  GROUP BY (CAST(extract(epoch from time) as INTEGER)/900)*900\nORDER BY count desc\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Last 15 min as % of # Ever Seen",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 66 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  to_timestamp((CAST(extract(epoch from time) as INTEGER)/900)*900) AS \"time\",\n  count(distinct core_id)::numeric * 100 / (SELECT count(distinct core_id) FROM powerwatch WHERE (product_id = 7008 OR product_id = 7009)) as \"count\"\nFROM\n  powerwatch\nWHERE\n  (time > now() - INTERVAL '15m')\n  GROUP BY (CAST(extract(epoch from time) as INTEGER)/900)*900\n  ORDER BY count desc\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "# Reporting in Last 3 Hours",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 66 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  to_timestamp((CAST(extract(epoch from time) as INTEGER)/10800)*10800) AS \"time\",\n  count(distinct core_id) \nFROM\n  powerwatch\nWHERE\n  (time > now() - INTERVAL '3h')\n  GROUP BY (CAST(extract(epoch from time) as INTEGER)/10800)*10800\nORDER BY count desc\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "# Reporting in Last 24 Hours",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 66 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  to_timestamp((CAST(extract(epoch from time) as INTEGER)/86400)*86400) AS \"time\",\n  count(distinct core_id) \nFROM\n  powerwatch\nWHERE\n  (time > now() - INTERVAL '1d')\n  GROUP BY (CAST(extract(epoch from time) as INTEGER)/86400)*86400\nORDER BY count desc\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "#  Reporting in Last 7 Days",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 66 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  to_timestamp((CAST(extract(epoch from time) as INTEGER)/604800)*604800) AS \"time\",\n  count(distinct core_id) \nFROM\n  powerwatch\nWHERE\n  (time > now() - INTERVAL '7d')\n  GROUP BY (CAST(extract(epoch from time) as INTEGER)/604800)*604800\nORDER BY count desc\nLIMIT 1\n"
    }
   ]
  }
 ]
}