sudo: false
language: node_js

addons:
  apt:
    packages:
      - expect

cache:
  directories:
    - "node_modules"
    - "$HOME/bin"

before_script:
  - true #npm install -g particle-cli
  - bash <( curl -sL https://particle.io/install-cli )
  - export PATH="$PATH:$HOME/bin"

script:
  - ./.particle-cli-login.expect "$particle_email" "$particle_password" "$(which particle)"
  - (pushd powerwatch/firmware/particle/plugwatch_C && particle compile electron firmware/)
