apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pgweb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pgweb
    spec:
      containers:
        - name: pgweb
          image: sosedoff/pgweb
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /
              port: 8081
          env:
          - name: SESSIONS
            value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: pgweb
  labels:
    app: pgweb
spec:
  ports:
   - port: 80
     targetPort: 8081
  selector:
   app: pgweb
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pgweb
  annotations:
    kubernetes.io/ingress.global-static-ip-name: pgweb
spec:
  backend:
    serviceName: pgweb
    servicePort: 80
  tls:
  - secretName: pgweb-tls
