apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerwatch-visualization
  labels:
    app: powerwatch-visualization
spec:
  template:
    metadata:
      labels:
        app: powerwatch-visualization
    spec:
      containers:
      - name: powerwatch-visualization
        image: lab11/powerwatch-visualization
        ports:
        - containerPort: 3765
        readinessProbe:
          httpGet:
            path: /
            port: 3765
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true

        - name: postgres-secret
          mountPath: /etc/config/postgres
          readOnly: true

      volumes:
      - name: config
        configMap:
          name: config
          items:
          - key: postgres.json
            path: postgres.json

      - name: postgres-secret
        secret:
          secretName: postgres-user-pass
          items:
          - key: username
            path: username
          - key: password
            path: password
---
apiVersion: v1
kind: Service
metadata:
  name: powerwatch-visualization
spec:
  type: NodePort
  selector:
    app: powerwatch-visualization
  ports:
  - port: 80
    targetPort: 3765
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: powerwatch-visualization
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ${POWERWATCH_VISUALIZATION_IP_ADDRESS}
spec:
  backend:
    serviceName: powerwatch-visualization
    servicePort: 80
