build:
  - name: ghana
    folder: plugwatch_C/firmware
    product_id: 7008
    output: build
  - name: predeploy
    folder: plugwatch_C/predeploy_firmware
    product_id: 7008
    output: ../../deployment-tools/provision
  - name: ghana
    folder: plugwatch_C/firmware
    product_id: 7009
    output: build
  - name: predeploy
    folder: plugwatch_C/predeploy_firmware
    product_id: 7009
    output: ../../deployment-tools/provision
  - name: ghana
    folder: plugwatch_F/firmware
    product_id: 7010
    output: build
  - name: predeploy
    folder: plugwatch_C/predeploy_firmware
    product_id: 7010
    output: ../../deployment-tools/provision
  - name: ghana
    folder: plugwatch_F/firmware
    product_id: 7011
    output: build
  - name: predeploy
    folder: plugwatch_C/predeploy_firmware
    product_id: 7011
    output: ../../deployment-tools/provision
  - name: ghana
    folder: plugwatch_F/firmware
    product_id: 8462
    output: build
  - name: predeploy
    folder: plugwatch_C/predeploy_firmware
    product_id: 8462
    output: ../../deployment-tools/provision
  - name: ghana
    folder: plugwatch_F/firmware
    product_id: 8797
    output: build
  - name: predeploy
    folder: plugwatch_C/predeploy_firmware
    product_id: 8798
    output: ../../deployment-tools/provision
  - name: testbed
    folder: plugwatch_C/firmware
    product_id: 7456
    output: build
  - name: testbed
    folder: plugwatch_F/firmware
    product_id: 8379
    output: build
  - name: predeploy
    folder: plugwatch_C/predeploy_firmware
    product_id: 7456
    output: ../../deployment-tools/provision
  - name: predeploy
    folder: plugwatch_C/predeploy_firmware
    product_id: 8379
    output: ../../deployment-tools/provision
  - name: venezuela
    folder: plugwatch_C/firmware
    product_id: 7233
    output: build
  - name: nigeria
    folder: plugwatch_C/firmware
    product_id: 7641
    output: build
  - name: jay
    folder: plugwatch_F/firmware
    product_id: 8605
    output: build
  - name: india
    folder: plugwatch_F/firmware
    product_id: 8604
    output: build
  - name: sierra-leone
    folder: plugwatch_F/firmware
    product_id: 8776
    output: build
