kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: timescale-pv-claim
  labels:
    app: timescale
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: timescale
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: timescale
    spec:
      containers:
        - name: timescale
          image: timescale/timescaledb
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: timescale-config
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: timescaledb
              subPath: data

            - mountPath: /docker-entrypoint-initdb.d/initialize-read-user.sh
              subPath: initialize-read-user.sh
              name: timescale-initialization
      volumes:
        - name: timescaledb
          persistentVolumeClaim:
            claimName: timescale-pv-claim

        - name: timescale-initialization
          configMap:
            name: timescale-initialization
            items:
            - key: initialize-read-user.sh
              path: initialize-read-user.sh
---
apiVersion: v1
kind: Service
metadata:
  name: timescale
  labels:
    app: timescale
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: timescale
