apiVersion: v1
kind: Secret
metadata:
  name: influx-config
type: Opaque
data:
  INFLUXDB_DB: 
  INFLUXDB_ADMIN_USER: 
  INFLUXDB_ADMIN_PASSWORD:
  INFLUXDB_USER: 
  INFLUXDB_USER_PASSWORD:
  INFLUXDB_READ_USER: 
  INFLUXDB_READ_USER_PASSWORD:
  INFLUXDB_HTTP_AUTH_ENABLED:
