apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pvc-snapshot
spec:
  schedule: 1 1 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pvc-snapshot
            image: lab11/pvc-snapshot:production

          restartPolicy: onFailure
