apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pvc-snapshot
spec:
  schedule: */5 * * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pvc-snapshot
            image: lab11/powerwatch-pvc-snapshot:production

          restartPolicy: onFailure
