apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mqtt
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
        - name: mqtt
          image: eclipse-mosquitto:1.6.2
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  labels:
    app: mqtt
spec:
  type: NodePort
  ports:
   - port: 1833
     targetPort: 1833
  selector:
   app: mqtt
